name: CI

on:
  schedule:
  - cron: 13 * * * 1-5

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.204' # SDK Version to use.
    - name: Run a multi-line script
      run: |
        git switch -c master
        choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
        dir
        dotnet run --project ${{ GITHUB_WORKSPACE }}\updater\updater.csproj        
        
    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUSH_BRANCH: 'master'
